name = IO-Directory-Watcher

[ReadmeFromPod]
; disable = true
filename = lib/IO/Directory/Watcher.pm6

[PruneFiles]
; match = ^ 'xt/'

[Release]
upload-to-cpan = false
git-push = false

[UploadToZef]
